apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-saas 
  region: ${AWS_REGION}
  version: "1.17"

availabilityZones: ["${AWS_REGION}a", "${AWS_REGION}b", "${AWS_REGION}c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  ssh:
    allow: true
    publicKeyName: eksworkshop

# To enable all of the control plane logs, uncomment below:
# # cloudWatch:
# #  clusterLogging:
# #    enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}
